version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_pass
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: blog-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
